---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: ""
    labels: 
      app: ""
  spec: 
    selector: 
      matchLabels: 
        app: ""
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: ""
      spec: 
        containers: 
          - 
            name: ""
            image: ""
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: ""
    labels: 
      app: ""
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: ""
